security:

  encoders:
    Symfony\Component\Security\Core\User\User: plaintext

  role_hierarchy:
    ROLE_USER: ROLE_USER
    ROLE_SUPER_USER: [ROLE_USER]
    ROLE_ADMIN: [ROLE_USER, ROLE_SUPER_USER, ROLE_ALLOWED_TO_SWITCH]

  providers:
    in_memory:
      memory:
        users:
          simoneguglielmi: { password: 'dld=P@$gE*33S>[vn}chhUf_5./&.S%;44^,(y', roles: 'ROLE_SUPER_USER' }
          admin: { password: 'admin', roles: 'ROLE_ADMIN' }

  firewalls:
    default:
      anonymous: false
      http_basic: ~
      provider: in_memory

  access_control:
    - { path: ^/api, roles: ROLE_USER }
