<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerM6xOpEO\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerM6xOpEO/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerM6xOpEO.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerM6xOpEO\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerM6xOpEO\App_KernelDevDebugContainer([
    'container.build_hash' => 'M6xOpEO',
    'container.build_id' => '93bcd006',
    'container.build_time' => 1600847996,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerM6xOpEO');
