<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3ZHzaAd\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3ZHzaAd/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container3ZHzaAd.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container3ZHzaAd\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container3ZHzaAd\App_KernelDevDebugContainer([
    'container.build_hash' => '3ZHzaAd',
    'container.build_id' => '2f5f7df4',
    'container.build_time' => 1601449908,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3ZHzaAd');
