<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOOwNCKl\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOOwNCKl/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOOwNCKl.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOOwNCKl\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOOwNCKl\App_KernelDevDebugContainer([
    'container.build_hash' => 'OOwNCKl',
    'container.build_id' => '1ddd6f5b',
    'container.build_time' => 1601381781,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOOwNCKl');
